name: 'Blossom CLI Uploader'
description: 'Upload files to Blossom using the blossom-cli tool'
author: 'OpenTollGate'

inputs:
  host:
    description: 'Blossom host URL'
    required: true
    default: 'https://blossom.swissdash.site'
  filePath:
    description: 'Path to the file to upload'
    required: true
  nostrPrivateKey:
    description: 'Nostr private key (must be in nsec format)'
    required: true
  cliVersion:
    description: 'Version of blossom-cli to use'
    required: false
    default: 'latest'

outputs:
  url:
    description: 'URL of the uploaded file'
    value: ${{ steps.upload.outputs.url }}
  hash:
    description: 'Hash of the uploaded file'
    value: ${{ steps.upload.outputs.hash }}
  success:
    description: 'Whether the upload was successful (true/false)'
    value: ${{ steps.upload.outputs.success }}
  error:
    description: 'Error message if upload failed'
    value: ${{ steps.upload.outputs.error }}

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Install blossom-cli
      id: install
      shell: bash
      run: |
        echo "Installing blossom-cli..."
        git clone https://github.com/girino/blossom-cli.git /tmp/blossom-cli
        cd /tmp/blossom-cli
        
        if [ "${{ inputs.cliVersion }}" != "latest" ]; then
          git checkout ${{ inputs.cliVersion }}
        fi
        
        # Modify go.mod to be compatible with our Go version
        sed -i 's/go 1.23.1/go 1.22/' go.mod
        sed -i '/toolchain/d' go.mod
        
        go mod download
        go build -o blossom-cli .

        # Try to build with modified dependencies
        echo "Building blossom-cli..."
        go mod tidy -compat=1.22
        
        # Try to downgrade dependencies if needed
        if ! go build -o blossom-cli .; then
          echo "Trying with downgraded dependencies..."
          go get github.com/nbd-wtf/go-nostr@v0.24.2
          go mod tidy -compat=1.22
          go build -o blossom-cli .
        fi

        # Move to a location in PATH
        sudo mv blossom-cli /usr/local/bin/
        
        echo "blossom-cli installed successfully"
    
    - name: Validate NSEC format
      shell: bash
      run: |
        # Check if the key is in nsec format
        if [[ ! "${{ inputs.nostrPrivateKey }}" =~ ^nsec ]]; then
          echo "Error: Private key must be in nsec format (starting with 'nsec')"
          echo "Please convert your hex key to nsec format before using this action"
          exit 1
        fi
    
    - name: Calculate file hash
      id: hash
      shell: bash
      run: |
        FILE_HASH=$(sha256sum "${{ inputs.filePath }}" | cut -d' ' -f1)
        echo "FILE_HASH=$FILE_HASH" >> $GITHUB_ENV
        echo "Original file hash: $FILE_HASH"
    
    - name: Upload file to Blossom
      id: upload
      shell: bash
      run: |
        # Create a temporary file for the private key
        echo "${{ inputs.nostrPrivateKey }}" > /tmp/nsec.key
        
        # Run the upload command with the correct format
        echo "Uploading file to Blossom..."
        echo "Command: blossom-cli upload -server \"${{ inputs.host }}\" -file \"${{ inputs.filePath }}\" -privkey \"$(cat /tmp/nsec.key)\""
        
        # Run with verbose output for debugging
        set -x
        RESULT=$(blossom-cli upload -server "${{ inputs.host }}" -file "${{ inputs.filePath }}" -privkey "$(cat /tmp/nsec.key)" 2>&1)
        UPLOAD_EXIT_CODE=$?
        set +x
        
        # Remove the private key file
        rm /tmp/nsec.key
        
        echo "Upload result: $RESULT"
        
        if [ $UPLOAD_EXIT_CODE -eq 0 ]; then
          # Extract URL from result
          URL=$(echo "$RESULT" | grep -oP 'URL: \K.*')
          
          if [ -n "$URL" ]; then
            echo "url=$URL" >> $GITHUB_OUTPUT
            echo "hash=$FILE_HASH" >> $GITHUB_OUTPUT
            echo "success=true" >> $GITHUB_OUTPUT
            
            echo "Upload successful!"
            echo "URL: $URL"
            echo "Hash: $FILE_HASH"
          else
            echo "success=false" >> $GITHUB_OUTPUT
            echo "error=Could not extract URL from result" >> $GITHUB_OUTPUT
            echo "Failed to extract URL from result"
            exit 1
          fi
        else
          echo "success=false" >> $GITHUB_OUTPUT
          echo "error=$RESULT" >> $GITHUB_OUTPUT
          echo "Upload failed with exit code $UPLOAD_EXIT_CODE"
          exit 1
        fi
