name: 'Blossom Uploader'
description: 'Upload files to Blossom with Nostr authentication'
author: 'OpenTollGate'

inputs:
  host:
    description: 'Blossom host URL'
    required: true
    default: 'https://blossom.swishdash.site'
  filePath:
    description: 'Path to the file to upload'
    required: true
  nostrPrivateKey:
    description: 'Nostr private key (nsec or hex format)'
    required: true
  contentType:
    description: 'Content type of the file'
    required: false
    default: ''
  uniqueId:
    description: 'Unique identifier to prevent auth reuse'
    required: false
    default: ''
  retries:
    description: 'Number of upload retries'
    required: false
    default: '3'

outputs:
  url:
    description: 'URL of the uploaded file'
    value: ${{ steps.upload.outputs.url }}
  hash:
    description: 'Hash of the uploaded file'
    value: ${{ steps.upload.outputs.hash }}
  size:
    description: 'Size of the uploaded file in bytes'
    value: ${{ steps.upload.outputs.size }}
  success:
    description: 'Whether the upload was successful (true/false)'
    value: ${{ steps.upload.outputs.success }}
  error:
    description: 'Error message if upload failed'
    value: ${{ steps.upload.outputs.error }}

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
      
    - name: Install dependencies
      shell: bash
      run: npm install nostr-tools@1.17.0 form-data node-fetch@2
      
    - name: Upload to Blossom
      id: upload
      shell: bash
      run: node ${{ github.action_path }}/upload.js
      env:
        FILE_PATH: ${{ inputs.filePath }}
        NSEC_KEY: ${{ inputs.nostrPrivateKey }}
        HOST: ${{ inputs.host }}
        UNIQUE_ID: ${{ inputs.uniqueId }}
        CONTENT_TYPE: ${{ inputs.contentType }}
        RETRIES: ${{ inputs.retries }}
        GITHUB_OUTPUT: $GITHUB_OUTPUT
