name: Test Direct Blossom Upload

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-direct-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate test file
        run: |
          dd if=/dev/urandom of=test-file.bin bs=1M count=1
          echo "ORIGINAL_HASH=$(sha256sum test-file.bin | cut -d' ' -f1)" >> $GITHUB_ENV
          echo "FILE_SIZE=$(stat -c%s test-file.bin)" >> $GITHUB_ENV

      - name: Upload to Blossom
        id: upload
        run: node direct-upload.js test-file.bin
        env:
          NSEC_KEY: ${{ secrets.NSEC }}
          CONTENT_TYPE: application/octet-stream
          UNIQUE_ID: ${{ github.run_id }}-${{ github.run_number }}
          GITHUB_OUTPUT: $GITHUB_OUTPUT

      - name: Verify upload
        if: steps.upload.outputs.success == 'true'
        run: |
          echo "✅ Upload successful!"
          echo "URL: ${{ steps.upload.outputs.url }}"
          echo "Hash: ${{ steps.upload.outputs.hash }}"
          
          # Download and verify
          curl -L "${{ steps.upload.outputs.url }}" -o downloaded-file.bin
          DOWNLOADED_HASH=$(sha256sum downloaded-file.bin | cut -d' ' -f1)
          
          if [ "$DOWNLOADED_HASH" == "${{ env.ORIGINAL_HASH }}" ]; then
            echo "✅ Hash verification successful!"
          else
            echo "❌ Hash verification failed!"
            echo "Original: ${{ env.ORIGINAL_HASH }}"
            echo "Downloaded: $DOWNLOADED_HASH"
            exit 1
          fi 